server:
  port: 4004

spring:
  cloud:
    gateway:
      routes:

        # =========================================================
        # AUTH SERVICE
        # =========================================================
        - id: auth-service-route
          uri: http://auth-service:4005
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        # =========================================================
        # PATIENT SERVICE
        # =========================================================
        - id: patient-service-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1
            - JwtValidation

        # =========================================================
        # APPOINTMENT SERVICE
        # =========================================================
        - id: appointment-service-route
          uri: http://appointment-service:4002
          predicates:
            - Path=/api/appointments/**
          filters:
            - StripPrefix=1
            - JwtValidation

        # =========================================================
        # BILLING SERVICE
        # =========================================================
        - id: billing-service-route
          uri: http://billing-service:4003
          predicates:
            - Path=/api/bills/**
          filters:
            - StripPrefix=1
            - JwtValidation

        # =========================================================
        # SWAGGER DOCS
        # =========================================================

        - id: auth-swagger
          uri: http://auth-service:4005
          predicates:
            - Path=/v3/api-docs/auth

          filters:
            - SetPath=/v3/api-docs

        - id: patient-swagger
          uri: http://patient-service:4000
          predicates:
            - Path=/v3/api-docs/patient

          filters:
            - SetPath=/v3/api-docs

        - id: appointment-swagger
          uri: http://appointment-service:4002
          predicates:
            - Path=/v3/api-docs/appointment

          filters:
            - SetPath=/v3/api-docs

        - id: billing-swagger
          uri: http://billing-service:4003
          predicates:
            - Path=/v3/api-docs/bills

          filters:
            - SetPath=/v3/api-docs

springdoc:
  api-docs:
    enabled: true

  swagger-ui:
    enabled: true
    path: /swagger-ui.html

    disable-swagger-default-url: true

    urls:
      - name: Auth Service
        url: /v3/api-docs/auth

      - name: Patient Service
        url: /v3/api-docs/patient

      - name: Appointment Service
        url: /v3/api-docs/appointment

      - name: Billing Service
        url: /v3/api-docs/bills