spring.datasource.url=jdbc:postgresql://patient-db:5432/patient_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always

spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.bootstrap-servers=kafka:9092
